from pathlib import Path
from typing import List
from robotlibcore import DynamicCore

class SwagLabsLibrary(DynamicCore):
    
    def __init__(self): ...
    def open_swaglabs_in_chrome_browser(self): ...
    def close_swaglabs(self):...
    def user_login_to_swaglabs(self, username: str, password: str):...
    def user_should_see_that_login_error_message_is(self, exp_err_msg: str):...
    def user_should_be_in_the_product_page(self):...
    